# -*- coding: utf-8 -*-
"""python for generative AI Btech core

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gXnVKgAyh6ruk6n-gKXeyOoud0tz4i2p
"""

x = 10

x

mysub = "python"
mysub

print(mysub)

_mycity = "Solan"
print(_mycity)

my_sub1 = "Generative AI"
print(my_sub1)

1my_sub = "Science"
print(1my_sub)

import keyword
print(keyword.kwlist)

x = 0
type(x)

y = 1.0
type(y)

z = 3+4j
type(z)

#string --data in the form text
a = "solan"
type(a)

#boolean -- it is used to store value in the form of True and False
a = True
type(a)

#None --it is define value means nothing
e = None
type(e)

#single quotes
my_sub = 'Generative AI'
type(my_sub)

#double quotes
my_college = "shoolini university"
type(my_college)

#triple quotes
my_sentence = ''' this sentence is multiple lines,
this is also a string'''
type(my_sentence)

#find the length of string
my_sub = "Machine learning"
len(my_sub)

my_sub[0]

my_sub[-16]

my_sub[-1]

my_sub[4]

my_sub

my_sub[0:7:1]

#concatenation--adding the string
first_name = "Amit"
last_name = "Kumar"
full_name = first_name +" "+ last_name
print(full_name)

#methods in string
#lower()--this method convert string into lower case
my_sub = "Machine Learning"
my_sub.lower()

lower(my_sub)

#upper()--this method convert string into upper case
my_sub.upper()

#count()--count particular character of the string
my_sub = "Machine Learning"
my_sub.count("a")

#list--it is sequence of item,every item separate by comma
#in list all item are enclosed by squarebracket
my_list = [98, 34, 56, "apple", True]
print(my_list)

type(my_list)

#list homogenius as well hetrogenious
my_list = [10, 4, 5,6 ,7] #homogenius
type(my_list)

list1 = ["apple", True, 2, 3.14, None] #hetrogenious
type(list1)

#indexing in list-- location of item
#positive indexing
my_list =[23,45, 98, 12, 56]
my_list[0]

len(my_list)

my_list[4]

#negative indexing
my_list =[23,45, 98, 12, 56]
my_list[-1]

print(my_list[-2])
print(my_list[-3])
print(my_list[-4])
print(my_list[-5])

#slicing in list
my_list = [2, 4, 7, 8, 9, 5, 3]
my_list[0:6:1]

#list print in apposite direction
my_list[: :-1]

my_list[:]

#list is concatenated
list1 = [3, 4,5, 6]
list2 = [6, 7, 8, 9]
my_list = list1+list2
print(my_list)

#function in list
my_list = [1, 2,3 ,4, 5,6]
min(my_list)

max(my_list)

sum(my_list)

list1 = [8, 6, 9, 3, 10, 5, 2]
sorted(my_list)

list1

my_list = [8, 6, 9, 3, 10, 5, 2]
sorted(my_list, reverse = True)

my_list = [8, 6, 9, 3, 10, 5, 2]
my_list.sort(reverse =True)

my_list

my_list = [98, 45, 56, 78]
my_list.append(100)
my_list

list1 = [67, 56, 43, 78]
list2 = [90, 89, 76]
list1.extend(list2)
list1

#pop()--
my_list = [78, 45, 35, 78, 90]
my_list.pop()

my_list

my_list.pop(2)

my_list

#remove
list1 = [67, 89, 45, 34]
list1.remove(89)

list1

my_dict = {"Name":"Kritika", "College":"shoolini"}
type(my_dict)

print(my_dict)

my_dict["Name"]

my_dict["College"]

#method in dictionary
#keys()--this method return keys of dictionary
list(my_dict.keys())

#values()--this method return values of dictionary
list(my_dict.values())

#items()--this method return item of the dictionary
list(my_dict.items())

#get()--this method find value and take key as a argument
my_dict.get("Name")

print(my_dict.get("Age", "Age is not present"))

#update()--this method update dictionary and take dictionary as argument
my_dict.update({"Age":20})
print(my_dict)

my_dict.update({"Name":"Jagat"})
print(my_dict)

#conditional statement
#if --this statement execute when condition is true
#elif--this statement execute when condition is true
#else--this statement execute when if and elif are not execute
age = int(input("enter your age: "))
if age>60:
  print("You are too old for marry")
elif age<18:
  print("You are too young for marry")
else:
  print("we will find perfact match for you")

#loop helps execute block of repeatedly
#for loop--this loop apply on sequence(list, string, tuple)
my_sub = "Python"
print(my_sub[0])
print(my_sub[1])
print(my_sub[2])
print(my_sub[3])
print(my_sub[4])
print(my_sub[5])

my_sub = "python"
for i in my_sub:
  print(i)

for i in range(len(my_sub)):
  print(my_sub[i], "->", i)

my_list = [89, 76, 45, 34]
for i in my_list:
  print(i)

#while loop--this loop execute until condition is true
i= 0
while i<5:
  print(i)
  i+=1

#loop control statement
#break-- this statement break the loop
i = 0
while i<5:
  i+=1
  if i == 3:
    break
  else:
    print(i)

#continue statement--skip current iteration
i = 0
while i<5:
  i+=1
  if i==3:
    continue
    #print(i)
  else:
    print(i)

#pass statement --only pass cursor
i = 0
while i<5:
  i+=1
  if i==3:
    pass
    print(i)
  else:
    print(i)

#user defined function without argument
def add():
  a = int(input("Enter first number: "))
  b = int(input("Enter second number:"))
  return a+b

print(add())

#positional argument
def Calculation(a, b):
  print("addition: ", a+b)
  print("Subtraction :", a-b)
  print("Multiplication: ", a*b)
  print("Division :", a/b)
  return "Calculation are complete"

print(Calculation(10, 5))

#default argument
def area_perimeter(width = 8, height = 4):
  area = width*height
  perimeter = 2*(width +height)
  return "Area is", area, "and perimeter is", perimeter

print(area_perimeter(10, 8))

#keyword argument
def interest(p, r, t):
  i = (p*r*t)/100
  return i

print(interest(t = 2, p = 1000, r= 10))

#mixed argument
print(interest(1000, t = 2, r = 10))

print(interest(p = 1000, r = 10, 2))

#non keyword variable length argument
def test(*args):
  print(args)
  print(len(args))
  print(type(args))

test(1, 2,3, 4,5, 6,7)

def sum_number(*args):
  sum = 0
  for num in args:
    sum+=num
  return sum

sum_number(4, 5, 6, 7)

#keyword variable length argument
def test(**kwargs):
  print(kwargs)
  print(len(kwargs))
  print(type(kwargs))

test(a = 10, b = 20, c = 30)

import numpy as np

oned_array = np.array([1, 2, 3])
print(oned_array)

row_vector = np.array([[1, 2, 3]])
print(row_vector)

column_vector = row_vector.transpose()
print(column_vector)

print(oned_array)

#ndim--dimension
oned_array.ndim

row_vector

row_vector.ndim

print(row_vector)

print(row_vector.ndim)
print(row_vector.shape)
print(row_vector.size)
print(row_vector.transpose())

rank_one_vector = np.array([1, 2, 3])
print(rank_one_vector)

twod_array = np.array([[1, 2, 3],[4, 5, 6]])
print(twod_array)

#indexing
print(twod_array[0][1])

print(twod_array[1][2])

print(twod_array)

print(twod_array[0:,0:2])

mat1 = np.matrix("1, 2, 3;4, 5, 6;7, 8, 9")
print(mat1)

random_array = np.random.random((3, 3))
print(random_array)

randint_array = np.random.randint(1, 10, (3, 3))
print(randint_array)

data = np.array([1,2, 3, 4])
power_data = np.power(data, 2)
print(power_data)

print(data)

exp_data = np.exp(data)
print(exp_data)

log_data = np.log(data)
print(log_data)

log2_data = np.log2(data)
print(log2_data)

log10_data = np.log10(data)
print(log10_data)

zeros_array = np.zeros((3, 3),dtype =int )
print(zeros_array)

ones_array = np.ones((2, 3),dtype = int)
print(ones_array)

#matplotlib
import matplotlib.pyplot as plt
import numpy as np

#line plot
xpoint = np.array([1, 3])
ypoint = np.array([2, 4])
plt.plot(xpoint, ypoint)
plt.show()

cgpa = np.array([6, 6.8, 7, 7.5, 8, 8.4, 8.8, 9, 9.5, 10])
package = np.array([4, 5.2, 5.5, 6, 6.5, 7, 7.5, 8, 8.5, 9])
font1 = {'family':'serif','color':'blue','size':20}
font2 = {'family':'serif','color':'darkred','size':15}
plt.plot(cgpa,package,"*:g", ms =15,mec = "orange",linewidth = 2)
plt.xlabel("cgpa",fontdict=font2)
plt.ylabel("package",fontdict=font2)
plt.title("CGPA VS PACKAGE",fontdict=font1)
plt.grid()
plt.show()

#bar plot--it work on numerical as well categorical data
import matplotlib.pyplot as plt
import numpy as np
fruit = np.array(["Apple", "Banana","Orange","Watermelon"])
fruit_number = np.array([100, 80,120, 50])
color = ["red","yellow","orange","green"]
plt.bar(fruit, fruit_number, color = color)
plt.show()

fruit = np.array(["Apple", "Banana","Orange","Watermelon"])
fruit_number = np.array([100, 80,120, 50])
color = ["red","yellow","orange","green"]
plt.barh(fruit, fruit_number, color = color)
plt.show()

#pie plot
x = np.array([25, 35, 20, 20])
my_labels = np.array(["Apple", "Banana", "Orange", "Watermelon"])
my_explode = np.array([0.2, 0, 0, 0])
plt.pie(x, labels = my_labels,explode = my_explode)
plt.legend(title = "Fruit",loc = "upper right")
plt.show()

#scatter plot--it is work on numerical data
x = np.array([1, 2, 3, 4, 5, 6, 7, 8])
y = np.array([200, 180, 160, 150, 130, 120, 110, 100])
plt.xlabel("Age of car")
plt.ylabel("Speed of car")
plt.title("Scatter plot")
plt.scatter(x, y)
plt.show()

#histogram --A histogram shows frequency distribution
x = np.random.randint(40, 100, (1, 200))
x = x.flatten()
print(x)
plt.xlabel("Marks of students")
plt.ylabel("Number of students")
plt.title("Histogram plot of students marks")
plt.hist(x,bins = 10)
plt.show()

import pandas as pd

my_series = pd.Series(["Apple", "Banana", "Orange", "Watermelon"], name="Fruit")
my_series

list_of_list = [["Amar",15],["Akbar",14], ["Anthony",13]]
df = pd.DataFrame(list_of_list, columns = ["Name", "Age"] )
df

import pandas as pd
df = pd.read_csv("/content/drive/MyDrive/data/imdb_data.csv")
df

#find the number of rows and columns
df.shape

#fetch data from top
df.head(2)

#fetch data from bottom
df.tail(2)

#fetch data point randomly
df.sample(10)

#find the information of the data
df.info()

#How does the data looklike mathematically
df.describe()

#find the number of columns
df.columns

#find the duplicate value
print(df.duplicated().sum())

#find the null value
df.isnull().sum()

df.columns

#indexing and slicing
df["title"]

df[["title", "budget","revenue", "original_language"]]

df[0:4]

df.iloc[0:4,0:3]

df.loc[0:4,["title","budget","revenue"]]

df["original_language"].unique()

hindi_movie = df[df["original_language"]=="hi"]
hindi_movie

hindi_movie.to_csv("hindi_movie.csv")

"""###Linear regression"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv("/content/placement.csv")
df

df.columns

plt.scatter(df["cgpa"],df["package"])
plt.xlabel("CGPA")
plt.ylabel("PACKAGE")
plt.show()

#find the null value
df.isnull().sum()

#find the independent and dependent feature
x = df.iloc[:,0]
y = df.iloc[:,1]
x

y

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2,
                                                random_state = 42 )
x_train

#train the model
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
lr

#x_train = x_train.values.reshape(-1, 1)
#x_train

lr.fit(x_train.values.reshape(-1, 1),y_train)

m = lr.coef_
m

b = lr.intercept_
b

cgpa = 9.5
package = m*cgpa +b
print(package)

